version: "3.9"
services:
  mariadb:
    image: mariadb
    restart: always
    ports:
      - 4406:3306
    volumes:
      - "/volume1/docker/mariadb/conf.d:/etc/mysql/conf.d"
      - "/volume1/docker/mariadb/data:/var/lib/mysql"
    environment:
      - MARIADB_DATABASE=meetus
      - MARIADB_ROOT_PASSWORD=meetuslovepower
      - MARIADB_ROOT_HOST=%
      - MARIADB_USER=meetus
      - MARIADB_PASSWORD=meetuslovepower
      - TZ=Asia/Seoul
    networks:
      - db-net  
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: Asia/Seoul
    ports:
      - "3000:3000"
    depends_on:
      - mariadb
    networks:
      - db-net  
networks:
    db-net: