kind: pipeline
type: docker
name: backend

steps:
- name: docker image build
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - cd backend
  - docker-compose up --force-recreate --build -d

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
- name: cache
  temp:
    medium: memory

trigger:
  branch:
    include:
      - "develop"
  event:
      include:
        - "push"

---
kind: pipeline
type: docker
name: front

steps:
- name: front-build
  image: node:16-alpine
  volumes:
  - name: cache
    path: /frontend/build
  commands:
  - cd frontend
  - npm ci
  - npm run build
- name: docker image build
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - cd frontend
  - docker-compose up --force-recreate --build -d

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
- name: cache
  temp:
    medium: memory

trigger:
  branch:
    include:
      - "develop"
  event:
      include:
        - "push"