kind: pipeline
type: docker
name: default

steps:
# - name: front-build
#   image: node:16.15.0-alpine3.15
#   volumes:
#   - name: cache
#     path: /frontend/build
#   commands:
#   - ls -al
#   - cd frontend
#   - npm ci
#   - npm run build
#   - ls -al
- name: docker image build
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - cd frontend
  - docker build --tag meet-us:latest .
  - docker stop meet-us
  - docker rm meet-us
  - docker run --name=meet-us --publish=6001:80 --detach=true meet-us:latest
  - docker ps -a

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
- name: cache
  temp:
    medium: memory